# test
# docker build
# docker login
# docker push

# AWS CodeBuild - cli command line commandon

# GitHub - kan köra command line commendon
#        - flora av kommandonsom man kan använda

name: Eriks Docker image Creation

#tigger AWS
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
#phases AWS
jobs:

  build:

    runs-on: ubuntu-latest
    # - = items i en lista
    steps:
    - uses: actions/checkout@v4
    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
        image: erikswe/test1120
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}